# config.yml
defaults:
  health: 20.0
  defense: 0.0
  strength: 0.0
  speed: 100.0
  crit-chance: 30.0
  crit-damage: 50.0
  wisdom: 100.0
  base-damage: 1.0
  damage-multiplier: 1.0
  healing: 100.0